export const API_BASE = process.env.NEXT_PUBLIC_API_BASE ?? "";
export type LeadPayload = { business_name: string; contact_name: string; email: string; phone?: string; website_url?: string; industry: string; city?: string; current_problem: string; monthly_lead_goal?: string; marketing_channels: string[]; source?: string; medium?: string; campaign?: string; consent: boolean; };
export async function createLead(payload: LeadPayload) { const backendPayload = { contact_name: payload.contact_name, email: payload.email, phone: payload.phone, business_name: payload.business_name, website_url: payload.website_url, industry: payload.industry, module_source: "dandelion_website", form_key: "audit_request", source: payload.source, medium: payload.medium, campaign: payload.campaign, consent: payload.consent, consent_text: "I agree to be contacted about this audit.", custom_fields: { city: payload.city, current_problem: payload.current_problem, monthly_lead_goal: payload.monthly_lead_goal, marketing_channels: payload.marketing_channels } }; const response = await fetch(`${API_BASE}/api/leads/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(backendPayload), cache: "no-store", }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail ?? "Unable to submit audit request."); } return response.json(); }
export async function trackEvent(event_type: string, metadata: Record<string, unknown> = {}) { const backendEvent = { event_type, path: typeof window !== "undefined" ? window.location.pathname : undefined, source: getParam("utm_source"), medium: getParam("utm_medium"), campaign: getParam("utm_campaign"), metadata, module_source: "dandelion_website" }; await fetch(`${API_BASE}/api/events/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(backendEvent), keepalive: true, }).catch(() => undefined); }
export async function getDashboard() { const response = await fetch(`${API_BASE}/api/admin/dashboard/`, { cache: "no-store", headers: adminHeaders(), }); if (!response.ok) throw new Error("Unable to load dashboard."); return response.json(); }
export async function getLeads() { const response = await fetch(`${API_BASE}/api/admin/leads/`, { cache: "no-store", headers: adminHeaders(), }); if (!response.ok) throw new Error("Unable to load leads."); return response.json(); }
export async function updateLeadStatus(leadId: string, status: string) { const response = await fetch(`${API_BASE}/api/admin/leads/${leadId}/status`, { method: "PATCH", headers: { "Content-Type": "application/json", ...adminHeaders() }, body: JSON.stringify({ status }), }); if (!response.ok) throw new Error("Unable to update lead."); return response.json(); }
function adminHeaders(): Record<string, string> { if (typeof window === "undefined") return {}; const key = window.localStorage.getItem("dandelion_admin_key"); return key ? { "X-Admin-Key": key } : {}; }
function getParam(name: string) { if (typeof window === "undefined") return undefined; return new URLSearchParams(window.location.search).get(name) ?? undefined; }
